'use client';
import { IndianRupee, CreditCard, Users, Sparkles } from 'lucide-react';

export default function MonetizationPage(){return <div className="container page"><div><h1 className="h1">Monetization plan</h1><p className="lead">Internal product strategy only. Keep the student experience free and monetize admin productivity.</p></div>
 <div className="card glow" style={{marginTop:24}}><div className="row"><span className="ico"><IndianRupee size={20}/></span><div><h2 className="h2">Recommended model: freemium SaaS</h2><p className="muted">The core loop—joining and playing quizzes—stays free. Paid value is placed around question-bank scale, analytics, collaboration and institutional controls.</p></div></div>
 <div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',marginTop:24}}>{[['Free','₹0','10 public quizzes/month · 100 saved questions · basic history'],['Teacher Plus','₹149/month · ₹1,490/year','Unlimited private quizzes · 1,000 questions · CSV · advanced analytics · branding'],['Campus','₹799/month · ₹7,990/year','Multiple admins · shared banks · institution analytics · lobby management · priority support']].map(x=><div className="card" key={x[0]}><span className="pill">{x[0]}</span><h3 style={{fontSize:25,margin:'14px 0 8px'}}>{x[1]}</h3><p className="muted" style={{lineHeight:1.6}}>{x[2]}</p></div>)}</div></div>
 <div className="grid" style={{gridTemplateColumns:'1fr 1fr',marginTop:16}}><div className="card"><h2 className="h2"><CreditCard size={18}/> Payments</h2><p className="muted" style={{lineHeight:1.7,marginTop:12}}>For India, integrate a domestic gateway such as Razorpay when billing is enabled. Budget around 2% + applicable GST for standard domestic gateway processing; confirm the live merchant agreement and current fee schedule before launch. Start with one-time/recurring subscriptions only after business KYC and tax setup.</p></div><div className="card"><h2 className="h2"><Users size={18}/> Go-to-market</h2><p className="muted" style={{lineHeight:1.7,marginTop:12}}>Launch Free + Teacher Plus first. Offer Campus after institutions repeatedly ask for shared administration. Use a 14-day Plus trial, annual billing at roughly 10 months of monthly pricing, and avoid charging students per quiz.</p></div></div>
 <div className="card" style={{marginTop:16}}><h2 className="h2"><Sparkles size={18}/> Product rules</h2><ul className="muted" style={{lineHeight:1.9}}><li>No ads inside active quiz rounds.</li><li>Never sell student answers, profiles or behavioral data.</li><li>Do not lock basic quiz participation behind payment.</li><li>Paid limits should target admin time-saving features, not classroom access.</li><li>Before taking payments, complete applicable Indian business, GST, invoicing and gateway compliance work.</li></ul></div>
 </div>}
